python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/2class_penu_dense201.json" --input_path '/media/disk/data/nih/images' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201_penu/checkpoint/checkpoint_best.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201_penu/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/2class_mass_dense201.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/data/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201_mass/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201_mass/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_dense201.json" --input_path '/media/disk/data/nih/images' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201/checkpoint/checkpoint_best.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/densenet/densenet201/visual/' --generate_num 100



# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b0.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b0/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b0/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b1.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b1/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b1/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b2.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b2/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b2/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b3.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b3/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b3/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b4.json" --input_path '/media/disk/data/nih/images' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b5.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b5/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b5/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b6.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b6/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b6/visual/' --generate_num 100

# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b4_224_vanilla_RMSprop.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4_224_pretrained_RMSprop/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4_224_pretrained_RMSprop/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b4_224_pretrained_RMSprop.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4_224_vanilla_RMSprop/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4_224_vanilla_RMSprop/visual/' --generate_num 100
# python3 main.py --json_path "/home/ipaa/Documents/yd/code/Chest/dk/configs/5class_efficient_b4_224_1channel_vanilla_RMSprop.json" --input_path '/home/ipaa/Documents/yd/code/Chest/dk/datasets/' --model_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4/checkpoint/checkpoint.pth.tar' --output_path '/home/ipaa/Documents/yd/code/Chest/dk/experiments/efficientnet/efficientnet_b4/visual/' --generate_num 100
